### PR TITLE
Propose my addition to steering committee

### PR DESCRIPTION
**Pull request by aj-stein-nist**
Permission to join the band? Let me know if there is a formal process and how I proceed, here or elsewhere, to state my case and expand the SCITT Community activities.

### CODE REVIEW

**Review by SteveLasker — APPROVED** [review]
It would be great to have you join, @aj-stein-nist 
LGTM

**Review by yogeshbdeshpande — APPROVED** [review]
LGTM!

Welcome AJ to the group 👍

**Comment by aj-stein-nist** [comment]
My GitHub account is changing soon and I updated the info, you may want to approve and merge this time.

FYI I lose access to this account tomorrow 23 August 2023 at 5 PM ET.

**Review by SteveLasker — APPROVED** [review]
LGTM to have A.J. join, as he's been a constant and collaborative contributor.

**Comment by SteveLasker** [comment]
> LGTM!
> 
> Welcome AJ to the group 👍

@yogeshbdeshpande, do you mind hitting the Approve, just so the record shows more than a comment?

**Review by OR13 — APPROVED** [review]

**Review by henkbirkholz — APPROVED** [review]

**Comment by henkbirkholz** [comment]
Is there a "new" A.J. now? :sweat_smile:

**Review by yogeshbdeshpande — APPROVED** [review]
LGTM!

**Comment by yogeshbdeshpande** [comment]
@SteveLasker While reviewing this file, I just noticed that some information has got too old!

Specifically looking at Kay Williams org.  We should tidy this up!

**Comment by kaywilliams** [comment]
Hey everyone, nice to see familiar names and faces in GitHub. @SteveLasker Steve reached out and asked if I'd like to step down from the steering committee given that I've moved on from Microsoft.  I think that makes sense.  Please go ahead and remove me.

It is great to see the project continue moving forward. Wishing you all the best!

**Comment by kkarunakaran89** [comment]
Hi everyone, @SteveLasker had reached out to me so please go ahead and remove me from maintainers list. All the best!

**Pull request merged**
